db-update:
	dotnet ef database update --project ChaosFinance.Infrastructure --startup-project ChaosFinance.API

migration:
	dotnet ef migrations add $(name) --project ChaosFinance.Infrastructure --startup-project ChaosFinance.API